### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by Johannes5** [mblode/alfred-trello#2]
> alfred-trello@2.0.0 postinstall /usr/local/lib/node_modules/alfred-trello
> alfy-init

/usr/local/lib/node_modules/alfred-trello/node_modules/alfy/init.js:5
(async () => {
       ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Darwin 18.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "alfred-trello"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! alfred-trello@2.0.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-trello@2.0.0 postinstall script 'alfy-init'.
npm ERR! This is most likely a problem with the alfred-trello package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     alfy-init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alfred-trello
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alfred-trello
npm ERR! There is likely additional logging output above.

> alfred-trello@2.0.0 preuninstall /usr/local/lib/node_modules/alfred-trello
> alfy-cleanup

/usr/local/lib/node_modules/alfred-trello/node_modules/alfy/cleanup.js:5
(async () => {
       ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm WARN continuing anyway alfred-trello@2.0.0 preuninstall: `alfy-cleanup`
npm WARN continuing anyway Exit status 1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johannes/npm-debug.log
JohannesMBP1093:~ johannes$

**Comment by mblode** [comment]
Thanks for the report, and sorry for the very late reply. Closing as won't-fix: the crash is from running the install under Node v4.5.0, which is years past end-of-life — alfy's `(async () => {})()` syntax requires a modern Node, so this is an environment issue rather than a bug in the workflow. On a current Node it wouldn't hit this. That said, the broader Alfred/alfy ecosystem (and this workflow) has long since moved on and this repo is no longer actively maintained, so I'd point anyone toward a currently-maintained Trello workflow. Leaving the repo up for reference/forks. Appreciate you flagging it.
